# Generated by Django 3.2.5 on 2021-07-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('n_mt', models.IntegerField(unique=True, verbose_name='Идентификатор в MT')),
                ('district', models.CharField(choices=[(None, 'Выберите район'), ('Заводской', 'Заводской'), ('Центральный', 'Центральный'), ('Куйбышевский', 'Куйбышевский'), ('Новоильинский', 'Новоильинский'), ('Орджоникидзевский', 'Орджоникидзевский'), ('Кузнецкий', 'Кузнецкий')], default='Выберите район', max_length=100, null=True, verbose_name='Район города')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('corpus', models.CharField(blank=True, max_length=3, null=True, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Контейнерная площадка',
                'verbose_name_plural': 'Контейнерные площадки',
                'ordering': ['n_mt'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('district', models.CharField(choices=[(None, 'Выберите район'), ('Заводской', 'Заводской'), ('Центральный', 'Центральный'), ('Куйбышевский', 'Куйбышевский'), ('Новоильинский', 'Новоильинский'), ('Орджоникидзевский', 'Орджоникидзевский'), ('Кузнецкий', 'Кузнецкий')], default='Выберите район', max_length=100, null=True, verbose_name='Район города')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('corpus', models.CharField(blank=True, max_length=3, null=True, verbose_name='Корпус')),
                ('unit', models.ForeignKey(blank=True, db_column='n_mt', null=True, on_delete=django.db.models.deletion.PROTECT, to='map.unit', verbose_name='Контейнерная площадка')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['street'],
            },
        ),
    ]
