# Generated by Django 3.2.4 on 2021-06-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('district', models.CharField(choices=[('Заводской', 'Zapsib'), ('Центральный', 'Centr')], default='С какого района?', max_length=100, null=True, verbose_name='Район города')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['n_mt'], 'verbose_name': 'Контейнерная площадка', 'verbose_name_plural': 'Контейнерные площадки'},
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес контейнерной площадки'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='n_mt', null=True, on_delete=django.db.models.deletion.PROTECT, to='map.unit', verbose_name='Контейнерная площадка'),
        ),
    ]
