# Generated by Django 3.2.4 on 2021-06-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[(None, 'Выберите район'), ('Заводской', 'Заводской'), ('Центральный', 'Центральный')], default='Выберите район', max_length=100, null=True, verbose_name='Район города'),
        ),
    ]
