# Generated by Django 3.2.4 on 2021-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
