# Generated by Django 3.2.4 on 2021-06-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_customer_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='korp',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Корпус'),
        ),
    ]
