# Generated by Django 3.2.4 on 2021-06-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_customer_korp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
