# Generated by Django 3.2.4 on 2021-06-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['street'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='korp',
            new_name='corpus',
        ),
    ]
